- name: install wget
  yum: name=wget state=present
#- name: backup yum-repo
#  raw: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
#- name: down 163yum repo
#  raw: wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.163.com/.help/CentOS6-Base-163.repo
#- name: yum makecache
#  raw: yum makecache
- name: create directory
  file: path={{ item.path }} state=directory
  with_items: 
    - { path: /application}
    - { path: /tools}
- name: install libselinux-python
  yum: name=libselinux-python state=present
- name: download nginx
  get_url: 
    url: http://nginx.org/download/nginx-1.10.2.tar.gz
    dest: /tools/
#- name: download openssl
#  get_url:
#    url: http://www.openssl.org/source/openssl-fips-2.0.10.tar.gz
#    dest: /tools
#- name: down zlib
#  get_url: 
#    url: http://zlib.net/zlib-1.2.11.tar.gz
#    dest: /tools
#- name: down pcre
#  get_url: 
#    url: https://ftp.pcre.org/pub/pcre/pcre-8.40.tar.gz
#    dest: /tools
- name: install pcre
  yum: name=pcre state=present
- name: install pcre-devel
  yum: name=pcre-devel state=present
- name: install gcc
  yum: name=gcc state=present
- name: install gcc-c++
  yum: name=gcc-c++ state=present
- name: install openssl
  yum: name=openssl state=present
- name: install openssl-devel
  yum: name=openssl-devel state=present
- name: install zlib
  yum: name=zlib state=present
- name: unarchive nginx
  unarchive:
    copy: no
    src: /tools/nginx-1.10.2.tar.gz
    dest: /application/
#- name: unar openssl
#  unarchive:
#    copy: no 
#    src: /tools/openssl-fips-2.0.10.tar.gz
#    dest: /application
#- name: unar pcre
#  unarchive:
#    copy: no
#    src: /tools/pcre-8.40.tar.gz
#    dest: /application/
#- name: unar zlib
#  unarchive:
#    copy: no 
#    src: /tools/zlib-1.2.11.tar.gz
#    dest: /application/
#- name: install openssl
#  raw: cd /application/openssl-fips-2.0.10 && ./config && make && make install
#- name: install pcre
#  raw: cd /application/pcre-8.40 && ./configure --prefix=/application/pcre && make && make install
#- name: install zlib
#  raw: cd /application/zlib-1.2.11 && ./configure --prefix=application/zlib && make && make install
- name: useradd nginx
  user: name=nginx state=present
- name: install nginx
  raw: cd /application/nginx-1.10.2 && ./configure --user=nginx --group=nginx --prefix=/application/nginx --with-http_stub_status_module --with-http_ssl_module && make && make install
- name: add system servicefile
  copy: src=files/nginx dest=/etc/init.d
- name: start nginx
  service: name=nginx state=restarted
  ignore_errors: True
- name: stop iptables
  service: name=iptables state=stopped

